
preset = 0

// title
deck_size = 0

card[1] = global.card[]
card[2] = global.card[]
card[3] = global.card[]
card[4] = global.card[]
card[5] = global.card[]
card[6] = global.card[]
card[7] = global.card[]
card[8] = global.card[]
card[9] = global.card[]
card[10] = global.card[]
card[11] = global.card[]
card[12] = global.card[]
card[13] = global.card[]
card[14] = global.card[]
card[15] = global.card[]
card[16] = global.card[]
card[17] = global.card[]
card[18] = global.card[]
card[19] = global.card[]
card[20] = global.card[]
card[21] = global.card[]
card[22] = global.card[]
card[23] = global.card[]
card[24] = global.card[]
card[25] = global.card[]
card[26] = global.card[]
card[27] = global.card[]
card[28] = global.card[]
card[29] = global.card[]
card[30] = global.card[]
card[31] = global.card[]
card[32] = global.card[]
card[33] = global.card[]
card[34] = global.card[]
card[35] = global.card[]
card[36] = global.card[]
card[37] = global.card[]
card[38] = global.card[]
card[39] = global.card[]
card[40] = global.card[]
card[41] = global.card[]
card[42] = global.card[]
card[43] = global.card[]
card[44] = global.card[]
card[45] = global.card[]
card[46] = global.card[]

